/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mx.edu.tecmm.elgrullo.ventitaapp.vistas.dialogs;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static mx.edu.tecmm.elgrullo.ventitaapp.utils.ButtonUtils.setColorButton;
import mx.edu.tecmm.elgrullo.ventitaapp.utils.ColorApp;
import static mx.edu.tecmm.elgrullo.ventitaapp.utils.ColorApp.BUTTON_PRIMARY;
import static mx.edu.tecmm.elgrullo.ventitaapp.utils.ColorApp.BUTTON_SELECTED;
import static mx.edu.tecmm.elgrullo.ventitaapp.utils.ColorApp.PRIMARY_COLOR;
import static mx.edu.tecmm.elgrullo.ventitaapp.utils.ColorApp.PRIMARY_LIGHT_TEXT;

/**
 *
 * @author coby_
 */
public abstract class DialogUpdateProducts extends javax.swing.JDialog {

    private DialogResult result = DialogResult.CANCEL; 
    
    /**
     * Creates new form DialogUpdateProducts
     */
    public DialogUpdateProducts(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initScreen(); 
    }
    
    /**
     * Metodo que inicializa la pantalla que se va estar  utilizando
     */
    private void initScreen(){
        lblTitle.setForeground(ColorApp.PRIMARY_LIGHT_TEXT);
        initButtons();
        lbErrorCodigoBarras.setVisible(false);
        lbErrorDescripcion.setVisible(false);
        lbErrorPrecio.setVisible(false);
    }
    
    /**
     * Medodo para estilizar los botones al inicio
     */
    private void initButtons(){
        setColorButton(btnGuadar, BUTTON_PRIMARY, PRIMARY_LIGHT_TEXT);
        setColorButton(btnCancelar, BUTTON_PRIMARY, PRIMARY_LIGHT_TEXT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnGuadar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lbErrorCodigoBarras = new javax.swing.JLabel();
        lbErrorDescripcion = new javax.swing.JLabel();
        lbErrorPrecio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(249, 250, 251));
        setMaximumSize(new java.awt.Dimension(337, 418));
        setMinimumSize(new java.awt.Dimension(337, 418));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(343, 418));

        jPanel1.setBackground(new java.awt.Color(10, 35, 66));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Codigo de barras:");

        txtCodigoBarras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoBarrasKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Descripción:");

        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Precio:");

        txtPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        btnGuadar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuadar.setText("GUARDAR");
        btnGuadar.setBorder(null);
        btnGuadar.setBorderPainted(false);
        btnGuadar.setFocusPainted(false);
        btnGuadar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnGuadarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnGuadarFocusLost(evt);
            }
        });
        btnGuadar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuadarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCancelarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCancelarFocusLost(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lbErrorCodigoBarras.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbErrorCodigoBarras.setForeground(new java.awt.Color(255, 102, 102));
        lbErrorCodigoBarras.setText("Este campo es requerido");

        lbErrorDescripcion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbErrorDescripcion.setForeground(new java.awt.Color(255, 102, 102));
        lbErrorDescripcion.setText("Este campo es requerido");

        lbErrorPrecio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbErrorPrecio.setForeground(new java.awt.Color(255, 102, 102));
        lbErrorPrecio.setText("Este campo es requerido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigoBarras)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecio)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtDescripcion)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuadar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbErrorCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbErrorDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbErrorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lbErrorCodigoBarras)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lbErrorDescripcion)
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lbErrorPrecio)
                .addGap(3, 3, 3)
                .addComponent(btnGuadar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuadarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuadarActionPerformed
       // validaciones 
       String codebar = txtCodigoBarras.getText();
       String description = txtDescripcion.getText();
       String precio = txtPrecio.getText();
       
       if(codebar.isEmpty()){
           lbErrorCodigoBarras.setVisible(true);
           txtCodigoBarras.requestFocus();
           return;
       }
       
       if(description.isEmpty()){
           lbErrorDescripcion.setVisible(true);
           txtDescripcion.requestFocus();
           return;
       }
       
       if(precio.isEmpty() || precio.equals(".") || precio.endsWith(".")){
           lbErrorPrecio.setVisible(true);
           txtPrecio.requestFocus();
           return;
       }
       double precioValue;
       
       try {
           precioValue = Double.parseDouble(precio); 
       } catch (Exception e) {
           precioValue = 0;
           lbErrorPrecio.setVisible(true);
           txtPrecio.requestFocus();
           return;
       }
       
       var res = processToProductUpdate(codebar, description, precioValue );
       
       if(res){
           JOptionPane.showMessageDialog(this, "Se agrego correctamente el producto", "Transacción correcta", JOptionPane.INFORMATION_MESSAGE);
           result = DialogResult.OK; 
           this.dispose();
       }else {
           JOptionPane.showMessageDialog(this, "Ocurrio un error al tratar de agregar el producto", "Transacción incorrecta", JOptionPane.ERROR_MESSAGE);
       }
       
    }//GEN-LAST:event_btnGuadarActionPerformed

    
    protected abstract boolean processToProductUpdate(String codebar, String description, double price);
    
    
    /**
     * Evento del boton de cancelar
     * @param evt 
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        result = DialogResult.CANCEL;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Metodo de type para el jtextfield de codigo de barras
     * @param evt 
     */
    private void txtCodigoBarrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarrasKeyTyped
        // TODO add your handling code here:
        ConvertToMayus(evt);
        lbErrorCodigoBarras.setVisible(false);
    }//GEN-LAST:event_txtCodigoBarrasKeyTyped

    /**
     * Metodo de type para el jtextfield de descripcion
     * @param evt 
     */
    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        // TODO add your handling code here:
        ConvertToMayus(evt);
        lbErrorDescripcion.setVisible(false);
    }//GEN-LAST:event_txtDescripcionKeyTyped

    /**
     * Evento para aceptar solo valores numericos
     * @param evt 
     */
    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        lbErrorPrecio.setVisible(false);
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
            evt.consume(); // Bloquea el caracter
            return;
        }
        
        JTextField txt = (JTextField) evt.getSource();
        if (c == '.' && txt.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    /**
     * Metodo cuando agarra el focus el boton 
     * @param evt 
     */
    private void btnGuadarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnGuadarFocusGained
        // TODO add your handling code here:
        activeButton(btnGuadar);
    }//GEN-LAST:event_btnGuadarFocusGained

    /**
     * Metodo que se usa cuando el boton pierde el foco
     * @param evt 
     */
    private void btnGuadarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnGuadarFocusLost
        // TODO add your handling code here:
        initButtons();
    }//GEN-LAST:event_btnGuadarFocusLost

    /**
     * Metodo que se activa cuando el boton cancelar se activa
     * @param evt 
     */
    private void btnCancelarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelarFocusGained
        // TODO add your handling code here:
         activeButton(btnCancelar);
    }//GEN-LAST:event_btnCancelarFocusGained

    /**
     * Metodo que se activa cuando el cancelar pierde el foco 
     * @param evt 
     */
    private void btnCancelarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelarFocusLost
        // TODO add your handling code here:
        initButtons();
    }//GEN-LAST:event_btnCancelarFocusLost
    
    /**
     * Metodo para selecconar el boton
     * @param btn 
     */
    private void activeButton(JButton btn){
        initButtons();
        setColorButton(btn, BUTTON_SELECTED, PRIMARY_COLOR);
    }
    /**
     * Metodo comun que usara para no repetir codigo en los dos eventos de los compontes de texto
     * @param evt 
     */
    private void ConvertToMayus(java.awt.event.KeyEvent evt){
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    } 
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Metodo para comunicar estado afuera">
        /**
         * Enumerador que sirve unicamente para saber si el dialog cumplio con su objetivo 
         */
        public enum DialogResult {
            OK,
            CANCEL
        }

        /**
         * Metodo que me permitira saber que resultado obtuvo el dialogo  
         * @return 
         */
         public DialogResult getResult() {
            return result;
        }
    // </editor-fold>
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuadar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbErrorCodigoBarras;
    private javax.swing.JLabel lbErrorDescripcion;
    private javax.swing.JLabel lbErrorPrecio;
    protected javax.swing.JLabel lblTitle;
    protected javax.swing.JTextField txtCodigoBarras;
    protected javax.swing.JTextField txtDescripcion;
    protected javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    
}
