/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.tecmm.elgrullo.ventitaapp.views;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import mx.edu.tecmm.elgrullo.ventitaapp.views.panels.PnlProducts;

/**
 *
 * @author coby_
 */
public class App extends javax.swing.JFrame {
    
    public static App mainFrame; 
    
    private static final Color btnBackgroundSelected = new Color(189, 9, 229); 
    private static final Color btnForegroundSelected = new Color(185, 191, 201);
    
    private static final Color btnBackground = new Color(204, 204, 255);
    private static final Color btnForeground = new Color(86,96,84);
    
    private JPanel mainPanel = null; 

    /**
     * Creates new form App
     */
    public App(String user) {
        initComponents();
        mainFrame = this;
        lblUsuario.setText(user);
        // acomodando la imagen 
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/logo.png"));
        ImageIcon iconLogo = new ImageIcon(getClass().getResource("/images/logogrande.png"));
        
        // Opcional: redimensionar la imagen si no tiene el tamaño deseado
        Image imagenEscalada = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
        jLogo.setIcon(new ImageIcon(imagenEscalada));
        
        imagenEscalada = iconLogo.getImage().getScaledInstance(400, 400, Image.SCALE_SMOOTH);
        jlabelLogo.setIcon(new ImageIcon(imagenEscalada));
        
        setActiveButtons(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpImg = new javax.swing.JPanel();
        jLogo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnProdcutos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        jlabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi ventita");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(180, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(180, 484));

        jpImg.setBackground(new java.awt.Color(0, 0, 153));

        jLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpImgLayout = new javax.swing.GroupLayout(jpImg);
        jpImg.setLayout(jpImgLayout);
        jpImgLayout.setHorizontalGroup(
            jpImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpImgLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpImgLayout.setVerticalGroup(
            jpImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(204, 204, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("usuario");

        btnProdcutos.setBackground(new java.awt.Color(204, 204, 255));
        btnProdcutos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProdcutos.setText("Productos");
        btnProdcutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdcutosActionPerformed(evt);
            }
        });

        btnVentas.setBackground(new java.awt.Color(204, 204, 255));
        btnVentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(204, 204, 255));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProdcutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProdcutos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(new java.awt.BorderLayout());

        jlabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jlabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelLogo.setToolTipText("");
        jlabelLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlabelLogo.setPreferredSize(new java.awt.Dimension(400, 400));
        pnlMain.add(jlabelLogo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdcutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdcutosActionPerformed
        System.out.println("Click");
        setActiveButtons(btnProdcutos);
        var pnl = new PnlProducts(); 
        updatePanelSection(pnl);

    }//GEN-LAST:event_btnProdcutosActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        setActiveButtons(btnVentas);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        setActiveButtons(btnReportes);
    }//GEN-LAST:event_btnReportesActionPerformed

    
    private void setActiveButtons(JButton selected){
        setColorButton(btnVentas, App.btnBackground, App.btnForeground);
        setColorButton(btnProdcutos, App.btnBackground, App.btnForeground);
        setColorButton(btnReportes, App.btnBackground, App.btnForeground);
        if(selected != null)
        {
            setColorButton(selected, btnBackgroundSelected, btnForegroundSelected);
        }
    }
    
    private void setColorButton(JButton button, Color background, Color foreground){
        button.setBackground(background);
        button.setForeground(foreground);
    }
    
    private void updatePanelSection(JPanel panel ){
        this.remove(pnlMain);
        pnlMain = panel; 
        this.add(pnlMain, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProdcutos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabelLogo;
    private javax.swing.JPanel jpImg;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
