package mx.edu.tecmm.elgrullo.ventitaapp.vistas.panels;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import mx.edu.tecmm.elgrullo.ventitaapp.controllers.DaoProducto;
import mx.edu.tecmm.elgrullo.ventitaapp.controllers.DaoVenta;
import mx.edu.tecmm.elgrullo.ventitaapp.models.DetalleVentas;
import mx.edu.tecmm.elgrullo.ventitaapp.models.Venta;
import static mx.edu.tecmm.elgrullo.ventitaapp.utils.ButtonUtils.setColorButton;
import static mx.edu.tecmm.elgrullo.ventitaapp.utils.ColorApp.BUTTON_PRIMARY;
import static mx.edu.tecmm.elgrullo.ventitaapp.utils.ColorApp.PRIMARY_LIGHT_TEXT;
import mx.edu.tecmm.elgrullo.ventitaapp.utils.JTextFieldUtil;
import static mx.edu.tecmm.elgrullo.ventitaapp.utils.TableUtils.configTable;
import mx.edu.tecmm.elgrullo.ventitaapp.utils.TimeUtils;

/**
 * Ventana de ventas para poder dar de alta 
 * @author coby_
 */
public class PnlVenta extends javax.swing.JPanel {

    private List<DetalleVentas> detalles = new ArrayList<>(); 
    /**
     * Creates new form PnlVenta
     */
    public PnlVenta() {
        initComponents();
        configTable(tblVenta);        
        setColorButton(btnGuardar, BUTTON_PRIMARY, PRIMARY_LIGHT_TEXT);
        setDate(); 
        SwingUtilities.invokeLater(() -> {
            txtCodigoBarras.requestFocus();
        });
        initSell();
    }
    
    
    /**
     * Metodo para procesar la venta
     */
    public void processSell(){
        long lastId = DaoVenta.getLastId();
        Venta venta = new Venta();
        venta.setId(lastId+1);
        venta.setFechaRegistro(new Date());
        double total = 0;
        
        for (DetalleVentas det : detalles) {
            venta.addDetalle(det);// <-- IMPORTANTE
             total += det.getPrice() * det.getCant();
        }
        
         venta.setTotal(total);
        
        boolean res = DaoVenta.register(venta);
        /// mandar imprimir un ticket
        JOptionPane.showMessageDialog(this, "Se registro correctamente", "Correcto",JOptionPane.INFORMATION_MESSAGE);
        initSell();
    }
    
    
    private void initSell(){
        detalles = new ArrayList<>();
        initTable();
        long lastId = DaoVenta.getLastId();
        lbFolio.setText("FOLIO: " + String.format("%05d", lastId+1));
    }
    
    /**
     * Inicializar la tabla con los datos que se tienen en la lista
     */
    private void initTable(){
        String[] columns = {"ID", "CANT", "PRODUCTO", "PRECIO"}; 
        String[][] data = new String[detalles.size()][]; 
        int index = 0; 
        for(var detalle: detalles){
            data[index] = detalle.toArray(); 
            index++; 
        }
        var model = new DefaultTableModel(data, columns); 
        tblVenta.setModel(model);
        // actualiza la venta 
        double total = detalles.stream().mapToDouble(DetalleVentas::getPrice).sum(); 
        lblTotal.setText(String.format("%.2f", total));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lbFolio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenta = new javax.swing.JTable();
        lblFecha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(249, 250, 251));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(10, 35, 66));
        jLabel1.setText("Ventas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(10, 35, 66));
        jLabel2.setText("TIPO DE VENTA: Venta al publico");

        txtCodigoBarras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarrasActionPerformed(evt);
            }
        });
        txtCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoBarrasKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(249, 250, 251));

        jPanel2.setBackground(new java.awt.Color(10, 35, 66));
        jPanel2.setMaximumSize(new java.awt.Dimension(270, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(270, 100));

        jLabel3.setBackground(new java.awt.Color(249, 250, 251));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 250, 251));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TOTAL DE LA VENTA");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(249, 250, 251));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0.0");

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnGuardar.setText("Vender");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lbFolio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbFolio.setForeground(new java.awt.Color(249, 250, 251));
        lbFolio.setText("FOLIO: 00001");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(lbFolio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbFolio)
                .addGap(91, 91, 91)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tblVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVenta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(10, 35, 66));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoBarras)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblFecha))
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para que solo acepte mayusculas 
     * @param evt 
     */
    private void txtCodigoBarrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarrasKeyTyped
        // TODO add your handling code here:
        JTextFieldUtil.convertToMayus(evt);
        
    }//GEN-LAST:event_txtCodigoBarrasKeyTyped

    /**
     * Evento para poder trabar con el codigo de barras
     * @param evt 
     */
    private void txtCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarrasActionPerformed
        String codebar = txtCodigoBarras.getText();
        var producto = DaoProducto.getByCodigoBarras(codebar);
        if(producto != null) {
            var detalle = new DetalleVentas();
            detalle.setCant(1);
            detalle.setCodebar(producto.getCodigobarras());
            detalle.setDescripcion(producto.getDescripcion());
            detalle.setPrice(producto.getPrecio());
            detalles.add(detalle); 
            initTable();
        } else{
            JOptionPane.showMessageDialog(this, "No se encontro el producto", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } 
        txtCodigoBarras.setText("");
    }//GEN-LAST:event_txtCodigoBarrasActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        processSell();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * Pone el letrero en la parte superior con la fecha 
     */
    private void setDate(){
        lblFecha.setText("CAJA 1: " + TimeUtils.getDateTodayWithoutTime());
    }
    
    /**
     * Permite aumentar la seleccion segun el incremento que se mande 
     * @param change incremento 
     */
    public void tableChangeSelected(int change){
        int currentSelected = tblVenta.getSelectedRow();
        int totalRows = tblVenta.getRowCount(); 
        if(totalRows == 0) return ; 
        if(currentSelected == -1){
            tblVenta.setRowSelectionInterval(0, 0);
            return; 
        }
        currentSelected += change; 
        
        if(currentSelected < 0 || currentSelected >= totalRows) return; 
        tblVenta.setRowSelectionInterval(currentSelected, currentSelected);
    }
    
    /**
     * Metodo que permite eliminar el registro que tenga seleccionado 
     */
    public void deleteSelected(){
        int currentSelected = tblVenta.getSelectedRow();
        if(currentSelected == -1) return; 
        String codebar = tblVenta.getValueAt(currentSelected, 0).toString(); 
        Optional<DetalleVentas> firstRow = detalles.stream().filter(detalle -> detalle.getCodebar().equalsIgnoreCase(codebar)).findFirst();        
        firstRow.ifPresent(detalles::remove);
        initTable();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFolio;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblVenta;
    protected javax.swing.JTextField txtCodigoBarras;
    // End of variables declaration//GEN-END:variables
}
