package mx.edu.tecmm.elgrullo.ventitaapp.vistas;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.Timer;
import mx.edu.tecmm.elgrullo.ventitaapp.utils.ImageUtils;

/**
 * Ventana principal que permite controlar todo el flujo de la aplicación 
 * @author coby_
 */
public class App extends javax.swing.JFrame {
    
    private static final Color PRIMARY_COLOR = new Color(10,35,66); 
    private static final Color SECONDARY_COLOR = new Color(30, 58, 138);
    private static final Color PRIMARY_ACCENT = new Color(29,78,216);
    
    private static final Color BUTTON_PRIMARY = new Color(30, 58, 138);
    private static final Color BUTTON_SELECTED = new Color(59, 130, 246);
    private static final Color BUTTON_PRIMARY_TEXT = new Color(255, 255, 255);
    
    private final int DELAY_TIMER = 30_000; 
    
    
    /**
     * Creates new form App
     */
    public App(String user) {
        initComponents();
        initScreen(user);         
    }

    
    public void initScreen(String user){
        imgLogoUser.setIcon(ImageUtils.getImageIcon(getClass(), "user_logo.png",150,150));
        lbUser.setText(user);
        /// buttons
        initButtons();
        actualizarFecha();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStatus = new javax.swing.JPanel();
        lbFecha = new javax.swing.JLabel();
        navPaanel = new javax.swing.JPanel();
        imgLogoUser = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        btnVentas = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        lbSaldoCaja = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Ventita");

        pnlStatus.setBackground(new java.awt.Color(30, 58, 138));
        pnlStatus.setMaximumSize(new java.awt.Dimension(32767, 40));
        pnlStatus.setMinimumSize(new java.awt.Dimension(100, 40));
        pnlStatus.setPreferredSize(new java.awt.Dimension(1013, 40));

        lbFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(255, 255, 255));
        lbFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbFecha.setText("jLabel3");

        javax.swing.GroupLayout pnlStatusLayout = new javax.swing.GroupLayout(pnlStatus);
        pnlStatus.setLayout(pnlStatusLayout);
        pnlStatusLayout.setHorizontalGroup(
            pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatusLayout.createSequentialGroup()
                .addContainerGap(547, Short.MAX_VALUE)
                .addComponent(lbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlStatusLayout.setVerticalGroup(
            pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatusLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lbFecha)
                .addContainerGap())
        );

        getContentPane().add(pnlStatus, java.awt.BorderLayout.PAGE_END);

        navPaanel.setBackground(new java.awt.Color(10, 35, 66));
        navPaanel.setMaximumSize(new java.awt.Dimension(180, 32767));
        navPaanel.setMinimumSize(new java.awt.Dimension(180, 100));
        navPaanel.setName(""); // NOI18N
        navPaanel.setPreferredSize(new java.awt.Dimension(180, 536));

        imgLogoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_logo.png"))); // NOI18N
        imgLogoUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbUser.setForeground(new java.awt.Color(255, 255, 255));
        lbUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUser.setText("jLabel1");

        btnVentas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setBorder(null);
        btnVentas.setBorderPainted(false);
        btnVentas.setFocusPainted(false);

        btnProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setBorder(null);
        btnProductos.setBorderPainted(false);
        btnProductos.setFocusPainted(false);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnReportes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(null);
        btnReportes.setBorderPainted(false);
        btnReportes.setFocusPainted(false);

        lbSaldoCaja.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSaldoCaja.setForeground(new java.awt.Color(255, 255, 255));
        lbSaldoCaja.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSaldoCaja.setText("$ 0.00");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Saldo:");

        javax.swing.GroupLayout navPaanelLayout = new javax.swing.GroupLayout(navPaanel);
        navPaanel.setLayout(navPaanelLayout);
        navPaanelLayout.setHorizontalGroup(
            navPaanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPaanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(navPaanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navPaanelLayout.createSequentialGroup()
                        .addGroup(navPaanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(navPaanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(navPaanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17))
                    .addGroup(navPaanelLayout.createSequentialGroup()
                        .addGroup(navPaanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(navPaanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imgLogoUser, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                            .addComponent(lbSaldoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        navPaanelLayout.setVerticalGroup(
            navPaanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPaanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(imgLogoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUser)
                .addGap(27, 27, 27)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSaldoCaja)
                .addContainerGap())
        );

        getContentPane().add(navPaanel, java.awt.BorderLayout.LINE_START);

        pnlMain.setBackground(new java.awt.Color(249, 250, 251));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        activeButton(btnProductos);
    }//GEN-LAST:event_btnProductosActionPerformed

    // <editor-fold defaultstate="collapsed" desc="Metodos utilitarios">
    
    /**
     * Metodo que permite reiniciar los colores de los botones y dejar el color a un boton especifico de marcado 
     * @param btn boton que quedara marcado 
     */
    private void activeButton(JButton btn){
        initButtons();
        setColorButton(btn, BUTTON_SELECTED, PRIMARY_COLOR);
    }
    
    /**
     * Metodo que reiniciar los colores de los botones
     */
    private void initButtons(){
        setColorButton(btnVentas, BUTTON_PRIMARY, BUTTON_PRIMARY_TEXT);
        setColorButton(btnProductos, BUTTON_PRIMARY, BUTTON_PRIMARY_TEXT);
        setColorButton(btnReportes, BUTTON_PRIMARY, BUTTON_PRIMARY_TEXT);
    }
    
    /**
     * Metodo que permite cambiar el color de un boton
     * @param button boton que cambia de color
     * @param back color del fondo del boton
     * @param fore color de texto del boton 
     */
    private void setColorButton(JButton button, Color back, Color fore){
        button.setBackground(back);
        button.setForeground(fore);
    }
    
    /**
     * Metodo que activa el timer que se ejecutara cada medio segundo
     */
    private void actualizarFecha(){
                
        updateLabelFecha();        
        new Timer(DELAY_TIMER, e -> updateLabelFecha()).start();
    }
    
    /**
     * Metodo para actualizar el label que esta en la barra de estatus
     */
    private void updateLabelFecha(){
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"); 
        String labelFecha = "El grullo, Jalisco " + LocalDateTime.now().format(formatter); 
        lbFecha.setText(labelFecha);
    }
    // </editor-fold>

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel imgLogoUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbSaldoCaja;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPanel navPaanel;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlStatus;
    // End of variables declaration//GEN-END:variables
}
